services:
  db:
    image: mariadb:10.6
    restart: always
    container_name: greenshop-db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./greenshop-db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - greenshop-net

  web:
    build: ./greenshop-web
    restart: always
    container_name: greenshop-web
    ports:
      - "80:80"
    depends_on:
      - db
    networks:
      - greenshop-net

networks:
  greenshop-net:
    driver: bridge
